"""GENERATED by scripts/gen_schemas.py from the vendored
JACKAL v1.7.0 package's plugin/hermes/tools.json — do not edit.
"""

TOOL_COUNT = 34

SCHEMAS = {
  "jackal_alg_cmp": {
    "description": "Order decision between two isolated real algebraic numbers (status=exact). NOT formal; no exact-cert emitted.",
    "name": "jackal_alg_cmp",
    "parameters": {
      "properties": {
        "a1": {
          "description": "First isolating interval lower bound (rational).",
          "type": "string"
        },
        "a2": {
          "description": "Second isolating interval lower bound (rational).",
          "type": "string"
        },
        "b1": {
          "description": "First isolating interval upper bound (rational).",
          "type": "string"
        },
        "b2": {
          "description": "Second isolating interval upper bound (rational).",
          "type": "string"
        },
        "p": {
          "description": "First defining polynomial in x.",
          "type": "string"
        },
        "q": {
          "description": "Second defining polynomial in x.",
          "type": "string"
        }
      },
      "required": [
        "p",
        "a1",
        "b1",
        "q",
        "a2",
        "b2"
      ],
      "type": "object"
    }
  },
  "jackal_alg_sign": {
    "description": "Exact sign of a Q[x] polynomial at a rational point (status=exact). NOT formal; no exact-cert emitted.",
    "name": "jackal_alg_sign",
    "parameters": {
      "properties": {
        "expression": {
          "description": "Polynomial expression in x within the poly fragment.",
          "type": "string"
        },
        "point": {
          "description": "Rational evaluation point (e.g. '3/2').",
          "type": "string"
        }
      },
      "required": [
        "expression",
        "point"
      ],
      "type": "object"
    }
  },
  "jackal_atan_rat_bound": {
    "description": "Emit a formal-bounded pure-Q atan(x) enclosure via the untrusted producer + Lean-proved checker. NO libm on the proof-decision path. Admits ONLY the exact form 'atan(x)' on a canonical rational interval; every other expression refuses without downgrade. v1.5.0 fragment extension.",
    "name": "jackal_atan_rat_bound",
    "parameters": {
      "properties": {
        "expression": {
          "description": "Must equal 'atan(x)' after whitespace normalization.",
          "type": "string"
        },
        "input_hi": {
          "description": "Interval upper bound (canonical rational, hi >= lo).",
          "type": "string"
        },
        "input_lo": {
          "description": "Interval lower bound as an integer or reduced rational.",
          "type": "string"
        }
      },
      "required": [
        "expression",
        "input_lo",
        "input_hi"
      ],
      "type": "object"
    }
  },
  "jackal_canon": {
    "description": "Canonical s-expression + SHA-256 of any parsed expression (status=exact). NOT formal: exact computation outside the Lean certificate chain; no exact-cert emitted.",
    "name": "jackal_canon",
    "parameters": {
      "properties": {
        "expression": {
          "description": "Any expression the engine grammar parses.",
          "type": "string"
        }
      },
      "required": [
        "expression"
      ],
      "type": "object"
    }
  },
  "jackal_claim": {
    "description": "Compile a structured jackal-claim-request-v1 into a canonical, content-addressed jackal-claim-bundle-v1 evidence graph through the deterministic policy router (v1.6.0 evidence kernel). Routes through the existing exact/formal/machine/unit lanes, emits a route trace naming candidates and refusal reasons, and refuses rather than silently downgrading (allow_fallback defaults false). The bundle is independently replayable via jackal_verify_bundle.",
    "name": "jackal_claim",
    "parameters": {
      "properties": {
        "request": {
          "description": "jackal-claim-request-v1 object: {schema, steps:[{id, op, ...}], root, policy?, nonce?, emitted_at_unix?, max_age_seconds?, expires_at_unix?}. Step ops: input, exact, enclose, gaussian, machine, interval_add/sub/mul/div, threshold, decision, convert, and, model, passthrough, attach.",
          "type": "object"
        }
      },
      "required": [
        "request"
      ],
      "type": "object"
    }
  },
  "jackal_cos_rat_bound": {
    "description": "Emit a formal-bounded pure-Q cos(x) enclosure via the untrusted producer + Lean-proved checker. NO libm on the proof-decision path. Admits ONLY the exact form 'cos(x)' on a canonical rational interval whose midpoint m satisfies |m| <= 1; every other expression refuses without downgrade. Shares the sin_rat producer (--op cos). v1.5.0 fragment extension.",
    "name": "jackal_cos_rat_bound",
    "parameters": {
      "properties": {
        "expression": {
          "description": "Must equal 'cos(x)' after whitespace normalization.",
          "type": "string"
        },
        "input_hi": {
          "description": "Interval upper bound (canonical rational, hi >= lo); midpoint (lo+hi)/2 must satisfy |m| <= 1.",
          "type": "string"
        },
        "input_lo": {
          "description": "Interval lower bound as an integer or reduced rational.",
          "type": "string"
        }
      },
      "required": [
        "expression",
        "input_lo",
        "input_hi"
      ],
      "type": "object"
    }
  },
  "jackal_crt": {
    "description": "Chinese remainder reconstruction over pairwise-coprime moduli, up to 16 pairs (status=exact). Emits a jackal-exact-cert-v1 certificate independently re-checkable by tools/exact_verify.py. NOT formal.",
    "name": "jackal_crt",
    "parameters": {
      "properties": {
        "args": {
          "description": "Space-separated residue/modulus pairs: 'r1 m1 r2 m2 [...]' (e.g. '2 3 3 5 2 7').",
          "type": "string"
        }
      },
      "required": [
        "args"
      ],
      "type": "object"
    }
  },
  "jackal_diff": {
    "description": "Symbolic d/dx with numeric self-verification (status=checked). Sampled agreement is a check, not a proof of identity.",
    "name": "jackal_diff",
    "parameters": {
      "properties": {
        "expression": {
          "description": "Expression in x; non-differentiable functions fail closed.",
          "type": "string"
        }
      },
      "required": [
        "expression"
      ],
      "type": "object"
    }
  },
  "jackal_divides": {
    "description": "Exact divisibility decision (status=exact). NOT formal; no exact-cert emitted.",
    "name": "jackal_divides",
    "parameters": {
      "properties": {
        "a": {
          "description": "Candidate divisor integer.",
          "type": "string"
        },
        "b": {
          "description": "Dividend integer.",
          "type": "string"
        }
      },
      "required": [
        "a",
        "b"
      ],
      "type": "object"
    }
  },
  "jackal_evaluate": {
    "description": "IEEE f64 expression evaluation (status=estimated). A plain number, honestly labeled: no bound, no proof.",
    "name": "jackal_evaluate",
    "parameters": {
      "properties": {
        "expression": {
          "description": "Full expression grammar incl. transcendental functions and constants.",
          "type": "string"
        }
      },
      "required": [
        "expression"
      ],
      "type": "object"
    }
  },
  "jackal_exact": {
    "description": "Exact big-rational arithmetic (status=exact). NOT formal: computationally exact, outside the Lean certificate chain.",
    "name": "jackal_exact",
    "parameters": {
      "properties": {
        "expression": {
          "description": "Integers, decimals, + - * / ^ (integer exponents), parentheses. Everything else refuses.",
          "type": "string"
        }
      },
      "required": [
        "expression"
      ],
      "type": "object"
    }
  },
  "jackal_exp_rat_bound": {
    "description": "Emit a formal-bounded pure-Q exp(x) enclosure via the untrusted producer + Lean-proved checker. NO libm on the proof-decision path. Admits ONLY the exact form 'exp(x)' on a canonical rational interval [lo, hi] (general-sign since v1.5.0); every other expression refuses without downgrade. v1.4.1 fragment extension.",
    "name": "jackal_exp_rat_bound",
    "parameters": {
      "properties": {
        "expression": {
          "description": "Must equal 'exp(x)' after whitespace normalization.",
          "type": "string"
        },
        "input_hi": {
          "description": "Interval upper bound (canonical rational, hi >= lo); the producer picks a Taylor degree with 2*hi <= n+1.",
          "type": "string"
        },
        "input_lo": {
          "description": "Interval lower bound as an integer or reduced rational; any sign (general-sign since v1.5.0).",
          "type": "string"
        }
      },
      "required": [
        "expression",
        "input_lo",
        "input_hi"
      ],
      "type": "object"
    }
  },
  "jackal_gaussian_integral": {
    "description": "Emit a zero-libm formal-bounded Gaussian integral receipt, rerun the pinned checker, or refuse without downgrade.",
    "name": "jackal_gaussian_integral",
    "parameters": {
      "properties": {
        "expression": {
          "description": "Exact canonical exp(-A*(x-mu)^2) expression; all other expressions refuse.",
          "type": "string"
        },
        "input_hi": {
          "description": "Integration upper bound as a canonical rational.",
          "type": "string"
        },
        "input_lo": {
          "description": "Integration lower bound as a canonical rational.",
          "type": "string"
        },
        "tolerance": {
          "description": "Maximum enclosure width as a positive canonical rational.",
          "type": "string"
        }
      },
      "required": [
        "expression",
        "input_lo",
        "input_hi",
        "tolerance"
      ],
      "type": "object"
    }
  },
  "jackal_integrate": {
    "description": "Fixed-grid Simpson + Richardson error estimate (status=estimated). Grid-limited: NOT a bound.",
    "name": "jackal_integrate",
    "parameters": {
      "properties": {
        "expression": {
          "description": "Integrand in x.",
          "type": "string"
        },
        "input_hi": {
          "description": "Upper limit.",
          "type": "string"
        },
        "input_lo": {
          "description": "Lower limit.",
          "type": "string"
        },
        "panels": {
          "description": "Panel count (e.g. '200').",
          "type": "string"
        }
      },
      "required": [
        "expression",
        "input_lo",
        "input_hi",
        "panels"
      ],
      "type": "object"
    }
  },
  "jackal_integrate_adaptive": {
    "description": "Adaptive Simpson with refusal semantics (status=estimated). Refuses when unconverged; agreement is still not a bound.",
    "name": "jackal_integrate_adaptive",
    "parameters": {
      "properties": {
        "expression": {
          "description": "Integrand in x.",
          "type": "string"
        },
        "input_hi": {
          "description": "Upper limit.",
          "type": "string"
        },
        "input_lo": {
          "description": "Lower limit.",
          "type": "string"
        },
        "tolerance": {
          "description": "Local tolerance (e.g. '1e-9').",
          "type": "string"
        }
      },
      "required": [
        "expression",
        "input_lo",
        "input_hi",
        "tolerance"
      ],
      "type": "object"
    }
  },
  "jackal_integrate_bound": {
    "description": "Certified interval enclosure of an integral (status=bounded). CONDITIONAL on the stated f64/libm rounding model; implementation campaign-tested, NOT mechanized. Never labeled formal. For a Lean-checked formal-bounded composed enclosure over the certified fragment, use jackal_integrate_bound_cert instead.",
    "name": "jackal_integrate_bound",
    "parameters": {
      "properties": {
        "expression": {
          "description": "Integrand in x.",
          "type": "string"
        },
        "input_hi": {
          "description": "Upper limit.",
          "type": "string"
        },
        "input_lo": {
          "description": "Lower limit.",
          "type": "string"
        },
        "tolerance": {
          "description": "Max enclosure width (e.g. '1e-6').",
          "type": "string"
        }
      },
      "required": [
        "expression",
        "input_lo",
        "input_hi",
        "tolerance"
      ],
      "type": "object"
    }
  },
  "jackal_integrate_bound_cert": {
    "description": "Emit a certified composed definite-integral formal receipt (v1.7 bound_step composition): untrusted exact-rational producer mirrors the engine's adaptive subdivision, the pinned Lean-proved jackal_int_cert_check re-checks the whole subdivision-tree certificate (theorem int_cert_sound), and the receipt is independently re-verified before returning. Certified fragment: num/var/neg/add/sub/mul/div/pow(0..4096)/sin/cos/abs in x. Everything else refuses. The weaker float lane jackal_integrate_bound stays status=bounded and is NOT this tool.",
    "name": "jackal_integrate_bound_cert",
    "parameters": {
      "properties": {
        "expression": {
          "description": "Integrand in the single variable x, restricted to the certified fragment (num/var/neg/add/sub/mul/div/pow/sin/cos/abs).",
          "type": "string"
        },
        "input_hi": {
          "description": "Integration upper bound as a canonical rational, strictly above input_lo.",
          "type": "string"
        },
        "input_lo": {
          "description": "Integration lower bound as an integer or reduced canonical rational (e.g. '0', '2/3').",
          "type": "string"
        },
        "tolerance": {
          "description": "Maximum enclosure width as a positive canonical rational (e.g. '1/100').",
          "type": "string"
        }
      },
      "required": [
        "expression",
        "input_lo",
        "input_hi",
        "tolerance"
      ],
      "type": "object"
    }
  },
  "jackal_ln_rat_bound": {
    "description": "Emit a formal-bounded pure-Q ln(x) enclosure via the untrusted producer + Lean-proved checker. NO libm on the proof-decision path. Admits ONLY the exact form 'ln(x)' on a canonical rational interval with lo > 0; every other expression refuses without downgrade. v1.5.0 fragment extension.",
    "name": "jackal_ln_rat_bound",
    "parameters": {
      "properties": {
        "expression": {
          "description": "Must equal 'ln(x)' after whitespace normalization.",
          "type": "string"
        },
        "input_hi": {
          "description": "Interval upper bound (canonical rational, hi >= lo).",
          "type": "string"
        },
        "input_lo": {
          "description": "Interval lower bound as an integer or reduced rational; must be > 0.",
          "type": "string"
        }
      },
      "required": [
        "expression",
        "input_lo",
        "input_hi"
      ],
      "type": "object"
    }
  },
  "jackal_mod_inv": {
    "description": "Modular inverse with product certificate (status=exact). Emits a jackal-exact-cert-v1 certificate independently re-checkable by tools/exact_verify.py. NOT formal.",
    "name": "jackal_mod_inv",
    "parameters": {
      "properties": {
        "a": {
          "description": "Integer to invert.",
          "type": "string"
        },
        "m": {
          "description": "Modulus integer >= 2; gcd(a, m) must be 1.",
          "type": "string"
        }
      },
      "required": [
        "a",
        "m"
      ],
      "type": "object"
    }
  },
  "jackal_mod_pow": {
    "description": "Modular exponentiation via square-and-multiply (status=exact). Emits a jackal-exact-cert-v1 certificate independently re-checkable by tools/exact_verify.py. NOT formal.",
    "name": "jackal_mod_pow",
    "parameters": {
      "properties": {
        "base": {
          "description": "Base integer.",
          "type": "string"
        },
        "exp": {
          "description": "Nonnegative exponent integer.",
          "type": "string"
        },
        "mod": {
          "description": "Modulus integer >= 1.",
          "type": "string"
        }
      },
      "required": [
        "base",
        "exp",
        "mod"
      ],
      "type": "object"
    }
  },
  "jackal_poly_canon": {
    "description": "Dense Q[x] canonical form, degree <= 64 (status=exact). Emits a jackal-exact-cert-v1 certificate independently re-checkable by tools/exact_verify.py. NOT formal.",
    "name": "jackal_poly_canon",
    "parameters": {
      "properties": {
        "expression": {
          "description": "Polynomial expression in x within the poly fragment.",
          "type": "string"
        }
      },
      "required": [
        "expression"
      ],
      "type": "object"
    }
  },
  "jackal_poly_eq": {
    "description": "Decidable polynomial identity over Q[x] (status=exact). Emits a jackal-exact-cert-v1 certificate independently re-checkable by tools/exact_verify.py. NOT formal.",
    "name": "jackal_poly_eq",
    "parameters": {
      "properties": {
        "lhs": {
          "description": "Left polynomial expression in x.",
          "type": "string"
        },
        "rhs": {
          "description": "Right polynomial expression in x.",
          "type": "string"
        }
      },
      "required": [
        "lhs",
        "rhs"
      ],
      "type": "object"
    }
  },
  "jackal_poly_gcd": {
    "description": "Monic polynomial gcd over Q[x] via Euclid (status=exact). Emits a jackal-exact-cert-v1 certificate independently re-checkable by tools/exact_verify.py. NOT formal.",
    "name": "jackal_poly_gcd",
    "parameters": {
      "properties": {
        "lhs": {
          "description": "Left polynomial expression in x.",
          "type": "string"
        },
        "rhs": {
          "description": "Right polynomial expression in x.",
          "type": "string"
        }
      },
      "required": [
        "lhs",
        "rhs"
      ],
      "type": "object"
    }
  },
  "jackal_prime_cert": {
    "description": "Pratt primality certificate or composite divisor witness, budgeted and fail-closed (status=exact; n <= 10^60, Pratt tree depth <= 64, nodes <= 512). Emits a jackal-exact-cert-v1 certificate independently re-checkable by tools/exact_verify.py. NOT formal.",
    "name": "jackal_prime_cert",
    "parameters": {
      "properties": {
        "n": {
          "description": "Integer >= 2, at most 61 digits.",
          "type": "string"
        }
      },
      "required": [
        "n"
      ],
      "type": "object"
    }
  },
  "jackal_range_bound": {
    "description": "Emit a formal-bounded receipt with the certificate embedded (or refuse).",
    "name": "jackal_range_bound",
    "parameters": {
      "properties": {
        "expression": {
          "description": "Anubis expression in the single variable x, restricted to the certified fragment.",
          "type": "string"
        },
        "input_hi": {
          "description": "Interval upper bound (canonical rational, hi >= lo).",
          "type": "string"
        },
        "input_lo": {
          "description": "Interval lower bound as an integer or reduced ℚ (e.g. '1', '2/3').",
          "type": "string"
        }
      },
      "required": [
        "expression",
        "input_lo",
        "input_hi"
      ],
      "type": "object"
    }
  },
  "jackal_ratfunc_canon": {
    "description": "Rational-function canonical form P/Q, gcd-reduced, monic denominator, explicit denominator-nonzero side condition (status=exact). Emits a jackal-exact-cert-v1 certificate independently re-checkable by tools/exact_verify.py. NOT formal.",
    "name": "jackal_ratfunc_canon",
    "parameters": {
      "properties": {
        "expression": {
          "description": "Rational-function expression in x within the ratfunc fragment.",
          "type": "string"
        }
      },
      "required": [
        "expression"
      ],
      "type": "object"
    }
  },
  "jackal_roots_isolate": {
    "description": "Sturm-sequence isolation of all distinct real roots (status=exact). Emits a jackal-exact-cert-v1 certificate independently re-checkable by tools/exact_verify.py. NOT formal.",
    "name": "jackal_roots_isolate",
    "parameters": {
      "properties": {
        "expression": {
          "description": "Polynomial expression in x within the poly fragment.",
          "type": "string"
        }
      },
      "required": [
        "expression"
      ],
      "type": "object"
    }
  },
  "jackal_sin_rat_bound": {
    "description": "Emit a formal-bounded pure-Q sin(x) enclosure via the untrusted producer + Lean-proved checker. NO libm on the proof-decision path. Admits ONLY the exact form 'sin(x)' on a canonical rational interval whose midpoint m satisfies |m| <= 1; every other expression refuses without downgrade. v1.5.0 fragment extension.",
    "name": "jackal_sin_rat_bound",
    "parameters": {
      "properties": {
        "expression": {
          "description": "Must equal 'sin(x)' after whitespace normalization.",
          "type": "string"
        },
        "input_hi": {
          "description": "Interval upper bound (canonical rational, hi >= lo); midpoint (lo+hi)/2 must satisfy |m| <= 1.",
          "type": "string"
        },
        "input_lo": {
          "description": "Interval lower bound as an integer or reduced rational.",
          "type": "string"
        }
      },
      "required": [
        "expression",
        "input_lo",
        "input_hi"
      ],
      "type": "object"
    }
  },
  "jackal_solve": {
    "description": "Bisection root with residual + first-order conditioning diagnostics (status=estimated).",
    "name": "jackal_solve",
    "parameters": {
      "properties": {
        "expression": {
          "description": "f(x) whose root is sought.",
          "type": "string"
        },
        "input_hi": {
          "description": "Bracket upper bound.",
          "type": "string"
        },
        "input_lo": {
          "description": "Bracket lower bound (sign change required).",
          "type": "string"
        }
      },
      "required": [
        "expression",
        "input_lo",
        "input_hi"
      ],
      "type": "object"
    }
  },
  "jackal_sqrt_rat_bound": {
    "description": "Emit a formal-bounded pure-Q sqrt(x) enclosure via the untrusted producer + Lean-proved checker. NO libm on the proof-decision path. Admits ONLY the exact form 'sqrt(x)' on a canonical rational interval; every other expression refuses without downgrade. v1.4.0 fragment extension.",
    "name": "jackal_sqrt_rat_bound",
    "parameters": {
      "properties": {
        "expression": {
          "description": "Must equal 'sqrt(x)' after whitespace normalization.",
          "type": "string"
        },
        "input_hi": {
          "description": "Interval upper bound (canonical rational, hi >= lo).",
          "type": "string"
        },
        "input_lo": {
          "description": "Interval lower bound as an integer or reduced rational (e.g. '2', '1/4'); must be >= 0.",
          "type": "string"
        }
      },
      "required": [
        "expression",
        "input_lo",
        "input_hi"
      ],
      "type": "object"
    }
  },
  "jackal_tanh_rat_bound": {
    "description": "Emit a formal-bounded pure-Q tanh enclosure via the untrusted composite producer + Lean-proved checker. NO libm on the proof-decision path. tanh is not an engine grammar token: admits ONLY the literal composite expression '1-2/(exp(2*x)+1)' (= tanh(x) mathematically) on a canonical rational interval with |lo|,|hi| <= 20; every other expression refuses without downgrade. v1.5.0 fragment extension.",
    "name": "jackal_tanh_rat_bound",
    "parameters": {
      "properties": {
        "expression": {
          "description": "Must equal '1-2/(exp(2*x)+1)' after whitespace normalization (the frozen tanh-defining composite).",
          "type": "string"
        },
        "input_hi": {
          "description": "Interval upper bound (canonical rational, hi >= lo); |hi| <= 20.",
          "type": "string"
        },
        "input_lo": {
          "description": "Interval lower bound as an integer or reduced rational; |lo| <= 20.",
          "type": "string"
        }
      },
      "required": [
        "expression",
        "input_lo",
        "input_hi"
      ],
      "type": "object"
    }
  },
  "jackal_verify_bundle": {
    "description": "Independently replay a jackal-claim-bundle-v1 against caller-pinned expectations (v1.6.0 evidence kernel). The standalone dependency-free verifier recomputes every canonical byte and hash, revalidates the DAG, re-runs embedded legacy evidence through the existing receipt/exact verifiers and pinned Lean checker, recomputes machine/unit mathematics, re-evaluates every inference rule and assurance-axis propagation, enforces consequence-class floors and policy, and recomputes the deterministic rendering. Returns verified | refused | indeterminate with exact reasons — never a generic green badge.",
    "name": "jackal_verify_bundle",
    "parameters": {
      "properties": {
        "bundle": {
          "description": "The jackal-claim-bundle-v1 object to replay.",
          "type": "object"
        },
        "expected_nonce": {
          "description": "Caller nonce; the bundle root must bind exactly this nonce.",
          "type": "string"
        },
        "expected_policy_sha256": {
          "description": "Caller-pinned SHA-256 of the canonical policy bytes.",
          "type": "string"
        },
        "expected_release_epoch": {
          "description": "Caller-pinned epoch (e.g. 'v1.6.0'); never copied from the bundle.",
          "type": "string"
        },
        "expected_root_proposition": {
          "description": "Caller-pinned canonical root proposition IR object.",
          "type": "object"
        },
        "verification_time_unix": {
          "description": "Caller-supplied verification time (unix seconds) for freshness/expiry checks.",
          "type": "string"
        }
      },
      "required": [
        "bundle",
        "expected_release_epoch",
        "expected_policy_sha256",
        "expected_root_proposition",
        "verification_time_unix"
      ],
      "type": "object"
    }
  },
  "jackal_verify_receipt": {
    "description": "Re-run the matching pinned Lean-proved range, Gaussian, or composed-integral (int_cert) checker over an embedded certificate.",
    "name": "jackal_verify_receipt",
    "parameters": {
      "properties": {
        "expected_command": {
          "description": "Caller-authorized operation: range-bound-cert or integrate.",
          "type": "string"
        },
        "expected_expression": {
          "description": "Exact raw expression supplied by the caller.",
          "type": "string"
        },
        "expected_input_hi": {
          "description": "Exact raw upper-bound token supplied by the caller.",
          "type": "string"
        },
        "expected_input_lo": {
          "description": "Exact raw lower-bound token supplied by the caller.",
          "type": "string"
        },
        "expected_release_epoch": {
          "description": "Caller-authorized release epoch, not copied from the receipt.",
          "type": "string"
        },
        "expected_tolerance": {
          "description": "Exact raw tolerance token; required for Gaussian and int_cert receipts and forbidden for range receipts.",
          "type": "string"
        },
        "receipt": {
          "description": "A jackal-formal-receipt-v1 JSON document.",
          "type": "object"
        }
      },
      "required": [
        "receipt",
        "expected_release_epoch",
        "expected_command",
        "expected_expression",
        "expected_input_lo",
        "expected_input_hi"
      ],
      "type": "object"
    }
  },
  "jackal_xgcd": {
    "description": "Extended gcd with Bezout certificate (status=exact). Emits a jackal-exact-cert-v1 certificate independently re-checkable by tools/exact_verify.py. NOT formal.",
    "name": "jackal_xgcd",
    "parameters": {
      "properties": {
        "a": {
          "description": "First integer.",
          "type": "string"
        },
        "b": {
          "description": "Second integer.",
          "type": "string"
        }
      },
      "required": [
        "a",
        "b"
      ],
      "type": "object"
    }
  }
}

ALL_TOOLS = sorted(SCHEMAS)
