#!/usr/bin/env python3
"""Generate schemas.py from the vendored JACKAL package's tools.json.

The Hermes tool schemas are DERIVED, not hand-maintained: this script reads
`plugin/hermes/tools.json` out of the vendored candidate package and emits a
deterministic `schemas.py`.  CI regenerates and requires byte equality, so
the registered surface can never drift from the sealed upstream surface.
"""
from __future__ import annotations

import io
import json
import tarfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PKG_BASE = "jackal-v1.7.3-macos-arm64.tar.gz"


def _parts() -> list:
    parts = sorted((ROOT / "pkg").glob(f"{PKG_BASE}.part*"))
    assert parts, "no vendored package parts found"
    for i, p in enumerate(parts):
        assert p.name == f"{PKG_BASE}.part{i:02d}", f"non-contiguous parts: {p.name}"
    return parts
PKG_DIRNAME = "jackal-v1.7.3-macos-arm64"
OUT = ROOT / "schemas.py"

_TYPE_MAP = {"string": "string", "object": "object"}


def load_tools() -> list[dict]:
    import io
    blob = b"".join(p.read_bytes() for p in _parts())
    with tarfile.open(fileobj=io.BytesIO(blob), mode="r:gz") as tf:
        member = tf.extractfile(f"{PKG_DIRNAME}/plugin/hermes/tools.json")
        assert member is not None
        doc = json.loads(member.read().decode("utf-8"))
    return doc["tools"]


def schema_for(tool: dict) -> dict:
    properties: dict = {}
    required: list[str] = []
    for arg, spec in tool["arguments"].items():
        prop: dict = {"type": _TYPE_MAP[spec["type"]]}
        help_text = spec.get("help", "").strip()
        if help_text:
            prop["description"] = help_text
        properties[arg] = prop
        if spec.get("required"):
            required.append(arg)
    parameters: dict = {"type": "object", "properties": properties}
    if required:
        parameters["required"] = required
    return {"name": tool["name"],
            "description": tool["description"],
            "parameters": parameters}


def main() -> int:
    tools = load_tools()
    schemas = {t["name"]: schema_for(t) for t in tools}
    names = sorted(schemas)
    lines = ['"""GENERATED by scripts/gen_schemas.py from the vendored',
             "JACKAL v1.7.3 candidate package catalog — do not edit.",
             '"""', "", f"TOOL_COUNT = {len(names)}", ""]
    lines.append("SCHEMAS = " + json.dumps(
        {n: schemas[n] for n in names}, indent=2, sort_keys=True,
        ensure_ascii=False))
    lines.append("")
    lines.append("ALL_TOOLS = sorted(SCHEMAS)")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"SCHEMAS_WRITTEN tools={len(names)} -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
